build:
    environment:
        ruby: '2.4.0'
    tests:
        override:
            -
                command: bundle exec rspec test.rb
                environment:
                    'SCRUTINIZER_CC_FILE': 'my-coverage'
                coverage:
                    file: 'my-coverage'
                    format: 'rb-cc'
checks:
    ruby: true